import { validateExpandedDetailsForAutoGenerated } from "../../scripts/content-generator/src/generator";
import type { GeneratedQuestion } from "../../scripts/content-generator/src/types";

function makeQuestion(overrides: Partial<GeneratedQuestion> = {}): GeneratedQuestion {
  return {
    id: "gen_q_001",
    phase: 2,
    type: "multiple_choice",
    question: "会議前、あなたはSlackの通知に気づいた。",
    choices: ["すぐ返す", "5分待つ", "既読スルー", "電話する"],
    correct_index: 1,
    explanation: "短く間を置くと衝動反応を減らしやすい。",
    actionable_advice: "今日1回、返信前に30秒だけ待ってから送る。",
    difficulty: "medium",
    xp: 15,
    source_id: "src_001",
    evidence_grade: "silver",
    expanded_details: {
      claim_type: "observation",
      evidence_type: "indirect",
      best_for: ["短文の返信で焦りやすい人"],
      limitations: ["緊急対応では適用しにくい"],
      citation_role: "反応抑制の背景として使う",
    },
    ...overrides,
  };
}

describe("content-generator expanded_details enforcement", () => {
  test("fails when expanded_details is missing", () => {
    const check = validateExpandedDetailsForAutoGenerated(makeQuestion({ expanded_details: undefined }));
    expect(check.ok).toBe(false);
    expect(check.reasons).toContain("expanded_details_missing");
  });

  test("fails when intervention details are incomplete", () => {
    const check = validateExpandedDetailsForAutoGenerated(
      makeQuestion({
        expanded_details: {
          claim_type: "intervention",
          evidence_type: "direct",
          best_for: ["先延ばし傾向がある人"],
          limitations: ["睡眠不足時は効きにくい"],
          citation_role: "短時間介入の背景",
          try_this: "10秒呼吸に注意を戻す",
        },
      })
    );

    expect(check.ok).toBe(false);
    expect(check.reasons).toContain("expanded_details.tiny_metric_missing");
    expect(check.reasons).toContain("expanded_details.comparator_missing");
    expect(check.reasons).toContain("expanded_details.fallback_missing");
  });

  test("passes when intervention details are complete", () => {
    const check = validateExpandedDetailsForAutoGenerated(
      makeQuestion({
        expanded_details: {
          claim_type: "intervention",
          evidence_type: "direct",
          best_for: ["先延ばし傾向がある人"],
          limitations: ["睡眠不足時は効きにくい"],
          citation_role: "短時間介入の背景",
          try_this: "10秒呼吸に注意を戻す",
          tiny_metric: {
            before_prompt: "いまの焦りは0-10でいくつ？",
            after_prompt: "10秒後の焦りは0-10でいくつ？",
            success_rule: "1下がれば成功",
            stop_rule: "変化がなければ今日は撤退",
          },
          comparator: {
            baseline: "何もしない",
            cost: "10秒",
          },
          fallback: {
            when: "逆に焦りが強まったら",
            next: "姿勢を変えて水を一口飲む",
          },
        },
      })
    );

    expect(check.ok).toBe(true);
    expect(check.reasons).toHaveLength(0);
  });
});

