// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import type { RawLessonJsonEntry } from "../../../types/lessonData";
import type { LessonContinuityMetadata } from "../../../types/lessonContinuity";
import type { LessonOperationalMetadata } from "../../../types/lessonOperational";
import health_l01_ja from "./health_l01.ja.json";

// English translations (fallback to ja if not available)
import health_l01_en from "./health_l01.en.json";

// Continuity metadata
import health_l01_continuity from "./health_l01.continuity.json";

// Evidence metadata
import health_l01_evidence from "./health_l01.evidence.json";

// Japanese (base) - always available
export const healthData_ja = [
  ...health_l01_ja,
];

// English - uses en where available, falls back to ja
export const healthData_en = [
  ...health_l01_en,
];

// Default export (ja for backward compatibility)
export const healthData = healthData_ja;

export const healthData_continuity: Record<string, LessonContinuityMetadata> = {
  "health_l01": health_l01_continuity as LessonContinuityMetadata,
};

export function getHealthDataContinuityForLesson(
  lessonId: string
): LessonContinuityMetadata | null {
  return healthData_continuity[lessonId] ?? null;
}

export function getHealthDataContinuityMap(): Record<string, LessonContinuityMetadata> {
  return healthData_continuity;
}

export const healthData_evidence: Record<string, LessonOperationalMetadata> = {
  "health_l01": health_l01_evidence as LessonOperationalMetadata,
};

export function getHealthDataEvidenceForLesson(
  lessonId: string
): LessonOperationalMetadata | null {
  return healthData_evidence[lessonId] ?? null;
}

export function getHealthDataEvidenceMap(): Record<string, LessonOperationalMetadata> {
  return healthData_evidence;
}

/**
 * Get health data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getHealthDataForLocale(locale: string): RawLessonJsonEntry[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'en') {
    return healthData_en;
  }

  // All other languages fall back to ja for now
  return healthData_ja;
}
