// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import health_l01_ja from "./health_l01.ja.json";

// Locale translations (fallback handled per locale export)
import health_l01_en from "./health_l01.en.json";
import health_l01_es from "./health_l01.es.json";
import health_l01_fr from "./health_l01.fr.json";

// Japanese (base) - always available
export const healthData_ja = [
  ...health_l01_ja,
];

// en - uses en where available, falls back to ja
export const healthData_en = [
  ...health_l01_en,
];

// es - uses es where available, falls back to en -> ja
export const healthData_es = [
  ...health_l01_es,
];

// fr - uses fr where available, falls back to en -> ja
export const healthData_fr = [
  ...health_l01_fr,
];

// Default export (ja for backward compatibility)
export const healthData = healthData_ja;

/**
 * Get health data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getHealthDataForLocale(locale: string): any[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'ja') {
    return healthData_ja;
  }

  if (lang === 'en') {
    return healthData_en;
  }
  if (lang === 'es') {
    return healthData_es;
  }
  if (lang === 'fr') {
    return healthData_fr;
  }

  return healthData_en;
}
