// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import type { RawLessonJsonEntry } from "../../../types/lessonData";
import type { LessonContinuityMetadata } from "../../../types/lessonContinuity";
import type { LessonOperationalMetadata } from "../../../types/lessonOperational";
import social_l01_ja from "./social_l01.ja.json";
import social_l02_ja from "./social_l02.ja.json";

// Continuity metadata
import social_l01_continuity from "./social_l01.continuity.json";
import social_l02_continuity from "./social_l02.continuity.json";

// Evidence metadata
import social_l01_evidence from "./social_l01.evidence.json";
import social_l02_evidence from "./social_l02.evidence.json";

// Japanese (base) - always available
export const socialData_ja = [
  ...social_l01_ja,
  ...social_l02_ja,
];

// Default export (ja for backward compatibility)
export const socialData = socialData_ja;

export const socialData_continuity: Record<string, LessonContinuityMetadata> = {
  "social_l01": social_l01_continuity as LessonContinuityMetadata,
  "social_l02": social_l02_continuity as LessonContinuityMetadata,
};

export function getSocialDataContinuityForLesson(
  lessonId: string
): LessonContinuityMetadata | null {
  return socialData_continuity[lessonId] ?? null;
}

export function getSocialDataContinuityMap(): Record<string, LessonContinuityMetadata> {
  return socialData_continuity;
}

export const socialData_evidence: Record<string, LessonOperationalMetadata> = {
  "social_l01": social_l01_evidence as LessonOperationalMetadata,
  "social_l02": social_l02_evidence as LessonOperationalMetadata,
};

export function getSocialDataEvidenceForLesson(
  lessonId: string
): LessonOperationalMetadata | null {
  return socialData_evidence[lessonId] ?? null;
}

export function getSocialDataEvidenceMap(): Record<string, LessonOperationalMetadata> {
  return socialData_evidence;
}

/**
 * Get social data for specified locale
 * No generated locale is active for this unit: every language reads the ja source.
 */
export function getSocialDataForLocale(_locale: string): RawLessonJsonEntry[] {
  return socialData_ja;
}
