// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import social_l01_ja from "./social_l01.ja.json";
import social_l02_ja from "./social_l02.ja.json";

// Locale translations (fallback handled per locale export)
import social_l01_en from "./social_l01.en.json";
import social_l02_en from "./social_l02.en.json";
import social_l01_es from "./social_l01.es.json";
import social_l02_es from "./social_l02.es.json";
import social_l01_fr from "./social_l01.fr.json";
import social_l02_fr from "./social_l02.fr.json";

// Japanese (base) - always available
export const socialData_ja = [
  ...social_l01_ja,
  ...social_l02_ja,
];

// en - uses en where available, falls back to ja
export const socialData_en = [
  ...social_l01_en,
  ...social_l02_en,
];

// es - uses es where available, falls back to en -> ja
export const socialData_es = [
  ...social_l01_es,
  ...social_l02_es,
];

// fr - uses fr where available, falls back to en -> ja
export const socialData_fr = [
  ...social_l01_fr,
  ...social_l02_fr,
];

// Default export (ja for backward compatibility)
export const socialData = socialData_ja;

/**
 * Get social data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getSocialDataForLocale(locale: string): any[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'ja') {
    return socialData_ja;
  }

  if (lang === 'en') {
    return socialData_en;
  }
  if (lang === 'es') {
    return socialData_es;
  }
  if (lang === 'fr') {
    return socialData_fr;
  }

  return socialData_en;
}
