export const genres = [
  { id: "mental", label: "メンタル", icon: "brain" },
  { id: "money", label: "お金", icon: "cash" },
  { id: "work", label: "仕事術", icon: "briefcase" },
  { id: "health", label: "健康", icon: "fitness" },
  { id: "social", label: "人間関係", icon: "people" },
  { id: "study", label: "学習法", icon: "book" },
];

export const trailsByGenre: Record<string, any[]> = {
  mental: [
    { id: "m1", status: "current", icon: "leaf", type: "lesson", lessonFile: "mental_l01" },
    { id: "m2", status: "locked", icon: "flower", type: "lesson", lessonFile: "mental_l02" },
    { id: "m3", status: "locked", icon: "sparkles", type: "lesson", lessonFile: "mental_l03" },
    { id: "m4", status: "locked", icon: "star", type: "lesson", lessonFile: "mental_l04" },
    { id: "m5", status: "locked", icon: "heart-circle", type: "lesson", lessonFile: "mental_l05" },
    { id: "m6", status: "locked", icon: "pulse", type: "lesson", lessonFile: "mental_l06" },
  ],
  money: [
    { id: "mo1", status: "current", icon: "cash", type: "lesson", lessonId: "money_lesson_1" },
    { id: "mo2", status: "locked", icon: "card", type: "lesson", lessonId: "money_lesson_2" },
    { id: "mo3", status: "locked", icon: "trending-up", type: "lesson", lessonId: "money_lesson_3" },
    { id: "mo4", status: "locked", icon: "wallet", type: "lesson", lessonId: "money_lesson_4" },
    { id: "mo5", status: "locked", icon: "calculator", type: "lesson", lessonId: "money_lesson_5" },
    { id: "mo6", status: "locked", icon: "bar-chart", type: "lesson", lessonId: "money_lesson_6" },
    { id: "mo7", status: "locked", icon: "pie-chart", type: "lesson", lessonId: "money_lesson_7" },
    { id: "mo8", status: "locked", icon: "analytics", type: "lesson", lessonId: "money_lesson_8" },
    { id: "mo9", status: "locked", icon: "stats-chart", type: "lesson", lessonId: "money_lesson_9" },
    { id: "mo10", status: "locked", icon: "trophy", type: "lesson", lessonId: "money_lesson_10" },
  ],
  work: [
    { id: "w1", status: "current", icon: "briefcase", type: "lesson", lessonId: "work_lesson_1" },
    { id: "w2", status: "locked", icon: "calendar", type: "lesson", lessonId: "work_lesson_2" },
    { id: "w3", status: "locked", icon: "clipboard", type: "lesson", lessonId: "work_lesson_3" },
    { id: "w4", status: "locked", icon: "timer", type: "lesson", lessonId: "work_lesson_4" },
    { id: "w5", status: "locked", icon: "checkmark-circle", type: "lesson", lessonId: "work_lesson_5" },
    { id: "w6", status: "locked", icon: "list", type: "lesson", lessonId: "work_lesson_6" },
    { id: "w7", status: "locked", icon: "create", type: "lesson", lessonId: "work_lesson_7" },
    { id: "w8", status: "locked", icon: "rocket", type: "lesson", lessonId: "work_lesson_8" },
    { id: "w9", status: "locked", icon: "flame", type: "lesson", lessonId: "work_lesson_9" },
    { id: "w10", status: "locked", icon: "trophy", type: "lesson", lessonId: "work_lesson_10" },
  ],
  health: [
    { id: "h1", status: "current", icon: "fitness", type: "lesson", lessonId: "health_lesson_1" },
    { id: "h2", status: "locked", icon: "heart", type: "lesson", lessonId: "health_lesson_2" },
    { id: "h3", status: "locked", icon: "nutrition", type: "lesson", lessonId: "health_lesson_3" },
    { id: "h4", status: "locked", icon: "bed", type: "lesson", lessonId: "health_lesson_4" },
    { id: "h5", status: "locked", icon: "water", type: "lesson", lessonId: "health_lesson_5" },
    { id: "h6", status: "locked", icon: "footsteps", type: "lesson", lessonId: "health_lesson_6" },
    { id: "h7", status: "locked", icon: "bicycle", type: "lesson", lessonId: "health_lesson_7" },
    { id: "h8", status: "locked", icon: "body", type: "lesson", lessonId: "health_lesson_8" },
    { id: "h9", status: "locked", icon: "medkit", type: "lesson", lessonId: "health_lesson_9" },
    { id: "h10", status: "locked", icon: "trophy", type: "lesson", lessonId: "health_lesson_10" },
  ],
  social: [
    { id: "s1", status: "current", icon: "people", type: "lesson", lessonId: "social_lesson_1" },
    { id: "s2", status: "locked", icon: "chatbubbles", type: "lesson", lessonId: "social_lesson_2" },
    { id: "s3", status: "locked", icon: "happy", type: "lesson", lessonId: "social_lesson_3" },
    { id: "s4", status: "locked", icon: "hand-left", type: "lesson", lessonId: "social_lesson_4" },
    { id: "s5", status: "locked", icon: "heart", type: "lesson", lessonId: "social_lesson_5" },
    { id: "s6", status: "locked", icon: "ear", type: "lesson", lessonId: "social_lesson_6" },
    { id: "s7", status: "locked", icon: "megaphone", type: "lesson", lessonId: "social_lesson_7" },
    { id: "s8", status: "locked", icon: "git-network", type: "lesson", lessonId: "social_lesson_8" },
    { id: "s9", status: "locked", icon: "ribbon", type: "lesson", lessonId: "social_lesson_9" },
    { id: "s10", status: "locked", icon: "trophy", type: "lesson", lessonId: "social_lesson_10" },
  ],
  study: [
    { id: "st1", status: "current", icon: "book", type: "lesson", lessonId: "study_lesson_1" },
    { id: "st2", status: "locked", icon: "school", type: "lesson", lessonId: "study_lesson_2" },
    { id: "st3", status: "locked", icon: "library", type: "lesson", lessonId: "study_lesson_3" },
    { id: "st4", status: "locked", icon: "bulb", type: "lesson", lessonId: "study_lesson_4" },
    { id: "st5", status: "locked", icon: "pencil", type: "lesson", lessonId: "study_lesson_5" },
    { id: "st6", status: "locked", icon: "glasses", type: "lesson", lessonId: "study_lesson_6" },
    { id: "st7", status: "locked", icon: "journal", type: "lesson", lessonId: "study_lesson_7" },
    { id: "st8", status: "locked", icon: "newspaper", type: "lesson", lessonId: "study_lesson_8" },
    { id: "st9", status: "locked", icon: "flash", type: "lesson", lessonId: "study_lesson_9" },
    { id: "st10", status: "locked", icon: "trophy", type: "lesson", lessonId: "study_lesson_10" },
  ],
};

export const league = [
  { id: "p1", name: "Miyu", xp: 1008 },
  { id: "p2", name: "Aleena", xp: 956 },
  { id: "p3", name: "Takeya", xp: 944 },
  { id: "p4", name: "Amanda", xp: 855 },
  { id: "p5", name: "Ms", xp: 738 },
  { id: "p6", name: "bobshih", xp: 735 },
  { id: "p7", name: "Chi", xp: 640 },
  { id: "p8", name: "Kai", xp: 520 },
  { id: "p9", name: "Rin", xp: 340 },
  { id: "p10", name: "Jun", xp: 180 },
  { id: "p11", name: "Sora", xp: 150 },
  { id: "p12", name: "Hana", xp: 120 },
  { id: "p13", name: "Yuki", xp: 100 },
  { id: "p14", name: "Kana", xp: 80 },
  { id: "p15", name: "Ryo", xp: 60 },
  { id: "p16", name: "Aoi", xp: 40 },
  { id: "p17", name: "Mei", xp: 20 },
];

export const promotionCut = 3;
export const relegationCut = 17;
