// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import type { RawLessonJsonEntry } from "../../../types/lessonData";
import type { LessonContinuityMetadata } from "../../../types/lessonContinuity";
import type { LessonOperationalMetadata } from "../../../types/lessonOperational";
import mental_l01_ja from "./mental_l01.ja.json";
import mental_l02_ja from "./mental_l02.ja.json";
import mental_l03_ja from "./mental_l03.ja.json";
import mental_l04_ja from "./mental_l04.ja.json";
import mental_l05_ja from "./mental_l05.ja.json";
import mental_l06_ja from "./mental_l06.ja.json";
import mental_m01_ja from "./mental_m01.ja.json";
import mental_m02_ja from "./mental_m02.ja.json";
import mental_m03_ja from "./mental_m03.ja.json";

// English translations (fallback to ja if not available)
import mental_l01_en from "./mental_l01.en.json";
import mental_l02_en from "./mental_l02.en.json";
import mental_l03_en from "./mental_l03.en.json";
import mental_l04_en from "./mental_l04.en.json";
import mental_l05_en from "./mental_l05.en.json";
import mental_l06_en from "./mental_l06.en.json";
import mental_m01_en from "./mental_m01.en.json";
import mental_m02_en from "./mental_m02.en.json";
import mental_m03_en from "./mental_m03.en.json";

// Continuity metadata
import mental_l01_continuity from "./mental_l01.continuity.json";
import mental_l02_continuity from "./mental_l02.continuity.json";
import mental_l03_continuity from "./mental_l03.continuity.json";
import mental_l04_continuity from "./mental_l04.continuity.json";
import mental_l05_continuity from "./mental_l05.continuity.json";
import mental_l06_continuity from "./mental_l06.continuity.json";
import mental_m01_continuity from "./mental_m01.continuity.json";
import mental_m02_continuity from "./mental_m02.continuity.json";
import mental_m03_continuity from "./mental_m03.continuity.json";

// Evidence metadata
import mental_l01_evidence from "./mental_l01.evidence.json";
import mental_l02_evidence from "./mental_l02.evidence.json";
import mental_l03_evidence from "./mental_l03.evidence.json";
import mental_l04_evidence from "./mental_l04.evidence.json";
import mental_l05_evidence from "./mental_l05.evidence.json";
import mental_l06_evidence from "./mental_l06.evidence.json";
import mental_m01_evidence from "./mental_m01.evidence.json";
import mental_m02_evidence from "./mental_m02.evidence.json";
import mental_m03_evidence from "./mental_m03.evidence.json";

// Japanese (base) - always available
export const mentalData_ja = [
  ...mental_l01_ja,
  ...mental_l02_ja,
  ...mental_l03_ja,
  ...mental_l04_ja,
  ...mental_l05_ja,
  ...mental_l06_ja,
  ...mental_m01_ja,
  ...mental_m02_ja,
  ...mental_m03_ja,
];

// English - uses en where available, falls back to ja
export const mentalData_en = [
  ...mental_l01_en,
  ...mental_l02_en,
  ...mental_l03_en,
  ...mental_l04_en,
  ...mental_l05_en,
  ...mental_l06_en,
  ...mental_m01_en,
  ...mental_m02_en,
  ...mental_m03_en,
];

// Default export (ja for backward compatibility)
export const mentalData = mentalData_ja;

export const mentalData_continuity: Record<string, LessonContinuityMetadata> = {
  "mental_l01": mental_l01_continuity as LessonContinuityMetadata,
  "mental_l02": mental_l02_continuity as LessonContinuityMetadata,
  "mental_l03": mental_l03_continuity as LessonContinuityMetadata,
  "mental_l04": mental_l04_continuity as LessonContinuityMetadata,
  "mental_l05": mental_l05_continuity as LessonContinuityMetadata,
  "mental_l06": mental_l06_continuity as LessonContinuityMetadata,
  "mental_m01": mental_m01_continuity as LessonContinuityMetadata,
  "mental_m02": mental_m02_continuity as LessonContinuityMetadata,
  "mental_m03": mental_m03_continuity as LessonContinuityMetadata,
};

export function getMentalDataContinuityForLesson(
  lessonId: string
): LessonContinuityMetadata | null {
  return mentalData_continuity[lessonId] ?? null;
}

export function getMentalDataContinuityMap(): Record<string, LessonContinuityMetadata> {
  return mentalData_continuity;
}

export const mentalData_evidence: Record<string, LessonOperationalMetadata> = {
  "mental_l01": mental_l01_evidence as LessonOperationalMetadata,
  "mental_l02": mental_l02_evidence as LessonOperationalMetadata,
  "mental_l03": mental_l03_evidence as LessonOperationalMetadata,
  "mental_l04": mental_l04_evidence as LessonOperationalMetadata,
  "mental_l05": mental_l05_evidence as LessonOperationalMetadata,
  "mental_l06": mental_l06_evidence as LessonOperationalMetadata,
  "mental_m01": mental_m01_evidence as LessonOperationalMetadata,
  "mental_m02": mental_m02_evidence as LessonOperationalMetadata,
  "mental_m03": mental_m03_evidence as LessonOperationalMetadata,
};

export function getMentalDataEvidenceForLesson(
  lessonId: string
): LessonOperationalMetadata | null {
  return mentalData_evidence[lessonId] ?? null;
}

export function getMentalDataEvidenceMap(): Record<string, LessonOperationalMetadata> {
  return mentalData_evidence;
}

/**
 * Get mental data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getMentalDataForLocale(locale: string): RawLessonJsonEntry[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'en') {
    return mentalData_en;
  }

  // All other languages fall back to ja for now
  return mentalData_ja;
}
