// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import type { RawLessonJsonEntry } from "../../../types/lessonData";
import type { LessonContinuityMetadata } from "../../../types/lessonContinuity";
import type { LessonOperationalMetadata } from "../../../types/lessonOperational";
import work_l01_ja from "./work_l01.ja.json";
import work_l02_ja from "./work_l02.ja.json";

// English translations (fallback to ja if not available)
import work_l01_en from "./work_l01.en.json";
import work_l02_en from "./work_l02.en.json";

// Continuity metadata
import work_l01_continuity from "./work_l01.continuity.json";
import work_l02_continuity from "./work_l02.continuity.json";

// Evidence metadata
import work_l01_evidence from "./work_l01.evidence.json";
import work_l02_evidence from "./work_l02.evidence.json";

// Japanese (base) - always available
export const workData_ja = [
  ...work_l01_ja,
  ...work_l02_ja,
];

// English - uses en where available, falls back to ja
export const workData_en = [
  ...work_l01_en,
  ...work_l02_en,
];

// Default export (ja for backward compatibility)
export const workData = workData_ja;

export const workData_continuity: Record<string, LessonContinuityMetadata> = {
  "work_l01": work_l01_continuity as LessonContinuityMetadata,
  "work_l02": work_l02_continuity as LessonContinuityMetadata,
};

export function getWorkDataContinuityForLesson(
  lessonId: string
): LessonContinuityMetadata | null {
  return workData_continuity[lessonId] ?? null;
}

export function getWorkDataContinuityMap(): Record<string, LessonContinuityMetadata> {
  return workData_continuity;
}

export const workData_evidence: Record<string, LessonOperationalMetadata> = {
  "work_l01": work_l01_evidence as LessonOperationalMetadata,
  "work_l02": work_l02_evidence as LessonOperationalMetadata,
};

export function getWorkDataEvidenceForLesson(
  lessonId: string
): LessonOperationalMetadata | null {
  return workData_evidence[lessonId] ?? null;
}

export function getWorkDataEvidenceMap(): Record<string, LessonOperationalMetadata> {
  return workData_evidence;
}

/**
 * Get work data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getWorkDataForLocale(locale: string): RawLessonJsonEntry[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'en') {
    return workData_en;
  }

  // All other languages fall back to ja for now
  return workData_ja;
}
