// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import work_l01_ja from "./work_l01.ja.json";
import work_l02_ja from "./work_l02.ja.json";

// Locale translations (fallback handled per locale export)
import work_l01_en from "./work_l01.en.json";
import work_l02_en from "./work_l02.en.json";
import work_l01_es from "./work_l01.es.json";
import work_l02_es from "./work_l02.es.json";
import work_l01_fr from "./work_l01.fr.json";
import work_l02_fr from "./work_l02.fr.json";

// Japanese (base) - always available
export const workData_ja = [
  ...work_l01_ja,
  ...work_l02_ja,
];

// en - uses en where available, falls back to ja
export const workData_en = [
  ...work_l01_en,
  ...work_l02_en,
];

// es - uses es where available, falls back to en -> ja
export const workData_es = [
  ...work_l01_es,
  ...work_l02_es,
];

// fr - uses fr where available, falls back to en -> ja
export const workData_fr = [
  ...work_l01_fr,
  ...work_l02_fr,
];

// Default export (ja for backward compatibility)
export const workData = workData_ja;

/**
 * Get work data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getWorkDataForLocale(locale: string): any[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'ja') {
    return workData_ja;
  }

  if (lang === 'en') {
    return workData_en;
  }
  if (lang === 'es') {
    return workData_es;
  }
  if (lang === 'fr') {
    return workData_fr;
  }

  return workData_en;
}
