// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import money_l01_ja from "./money_l01.ja.json";

// Locale translations (fallback handled per locale export)
import money_l01_en from "./money_l01.en.json";
import money_l01_es from "./money_l01.es.json";
import money_l01_fr from "./money_l01.fr.json";

// Japanese (base) - always available
export const moneyData_ja = [
  ...money_l01_ja,
];

// en - uses en where available, falls back to ja
export const moneyData_en = [
  ...money_l01_en,
];

// es - uses es where available, falls back to en -> ja
export const moneyData_es = [
  ...money_l01_es,
];

// fr - uses fr where available, falls back to en -> ja
export const moneyData_fr = [
  ...money_l01_fr,
];

// Default export (ja for backward compatibility)
export const moneyData = moneyData_ja;

/**
 * Get money data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getMoneyDataForLocale(locale: string): any[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'ja') {
    return moneyData_ja;
  }

  if (lang === 'en') {
    return moneyData_en;
  }
  if (lang === 'es') {
    return moneyData_es;
  }
  if (lang === 'fr') {
    return moneyData_fr;
  }

  return moneyData_en;
}
