// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import money_l01_ja from "./money_l01.ja.json";

// English translations (fallback to ja if not available)
import money_l01_en from "./money_l01.en.json";

// Japanese (base) - always available
export const moneyData_ja = [
  ...money_l01_ja,
];

// English - uses en where available, falls back to ja
export const moneyData_en = [
  ...money_l01_en,
];

// Default export (ja for backward compatibility)
export const moneyData = moneyData_ja;

/**
 * Get money data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getMoneyDataForLocale(locale: string): any[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'en') {
    return moneyData_en;
  }

  // All other languages fall back to ja for now
  return moneyData_ja;
}
