// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import money_l01_ja from "./money_l01.ja.json";

// Japanese (base) - always available
export const moneyData_ja = [
  ...money_l01_ja,
];

// Default export (ja for backward compatibility)
export const moneyData = moneyData_ja;
