// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import study_l01_ja from "./study_l01.ja.json";

// English translations (fallback to ja if not available)
import study_l01_en from "./study_l01.en.json";

// Japanese (base) - always available
export const studyData_ja = [
  ...study_l01_ja,
];

// English - uses en where available, falls back to ja
export const studyData_en = [
  ...study_l01_en,
];

// Default export (ja for backward compatibility)
export const studyData = studyData_ja;

/**
 * Get study data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getStudyDataForLocale(locale: string): any[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'en') {
    return studyData_en;
  }

  // All other languages fall back to ja for now
  return studyData_ja;
}
