// AUTO-GENERATED by scripts/gen-lesson-locale-index.js — do not edit manually
import type { RawLessonJsonEntry } from "../../../types/lessonData";
import type { LessonContinuityMetadata } from "../../../types/lessonContinuity";
import type { LessonOperationalMetadata } from "../../../types/lessonOperational";
import study_l01_ja from "./study_l01.ja.json";

// English translations (fallback to ja if not available)
import study_l01_en from "./study_l01.en.json";

// Continuity metadata
import study_l01_continuity from "./study_l01.continuity.json";

// Evidence metadata
import study_l01_evidence from "./study_l01.evidence.json";

// Japanese (base) - always available
export const studyData_ja = [
  ...study_l01_ja,
];

// English - uses en where available, falls back to ja
export const studyData_en = [
  ...study_l01_en,
];

// Default export (ja for backward compatibility)
export const studyData = studyData_ja;

export const studyData_continuity: Record<string, LessonContinuityMetadata> = {
  "study_l01": study_l01_continuity as LessonContinuityMetadata,
};

export function getStudyDataContinuityForLesson(
  lessonId: string
): LessonContinuityMetadata | null {
  return studyData_continuity[lessonId] ?? null;
}

export function getStudyDataContinuityMap(): Record<string, LessonContinuityMetadata> {
  return studyData_continuity;
}

export const studyData_evidence: Record<string, LessonOperationalMetadata> = {
  "study_l01": study_l01_evidence as LessonOperationalMetadata,
};

export function getStudyDataEvidenceForLesson(
  lessonId: string
): LessonOperationalMetadata | null {
  return studyData_evidence[lessonId] ?? null;
}

export function getStudyDataEvidenceMap(): Record<string, LessonOperationalMetadata> {
  return studyData_evidence;
}

/**
 * Get study data for specified locale with fallback
 * Fallback order: requested -> en -> ja
 */
export function getStudyDataForLocale(locale: string): RawLessonJsonEntry[] {
  const lang = locale.split('-')[0].toLowerCase();

  if (lang === 'en') {
    return studyData_en;
  }

  // All other languages fall back to ja for now
  return studyData_ja;
}
