name: Release From Private Source

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0"  # 毎週月曜 08:00 JST

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public (this) repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Clone PRIVATE source repo (read-only)
        run: |
          git clone https://x-access-token:${{ secrets.SOURCE_TOKEN }}@github.com/shin2721/shin2721-psych-duo-source-Private.git source_repo

      - name: Build packs with script in PRIVATE repo
        run: |
          cd source_repo
          # 両対応: .mjs があればそれ、なければ .ts は失敗するので念のためチェック
          if [ -f scripts/build_packs.mjs ]; then
            node scripts/build_packs.mjs
          elif [ -f scripts/build_packs.ts ]; then
            echo "ERROR: scripts/build_packs.mjs が無い。前チャット通り .mjs にしてね。"
            exit 1
          else
            echo "ERROR: build_packs スクリプトが見つからない"
            exit 1
          fi
          ls -la dist

      - name: Sync dist/* into PUBLIC repo
        run: |
          rsync -av --delete source_repo/dist/ ./  # manifest.json と packs/ が直下に来る

      - name: Create commit & tag
        run: |
          git config user.name "psych-duo-bot"
          git config user.email "actions@users.noreply.github.com"

          # 変更があるときだけ commit
          if git status --porcelain | grep .; then
            git add .
            TAG="packs-$(date -u +'%Y%m%d-%H%M')"
            git commit -m "release: update packs ($TAG)"
            git tag -a "$TAG" -m "packs release $TAG"
            git push origin HEAD:main --tags
          else
            echo "No changes to publish."
          fi
